version: '3.8'

services:
  backend:
    build: .
    container_name: backend
    ports:
      - "8000:8000"  # auth
      - "8001:8001"  # consultas
      - "80:80"      # api-gateway con nginx
    depends_on:
      - dynamodb
    volumes:
      - .:/app
    environment:
      - ENV=production
    env_file:
      - .env

  dynamodb:
    image: amazon/dynamodb-local
    container_name: dynamodb
    ports:
      - "8003:8003"
    volumes:
      - dynamodb_data:/home/dynamodblocal/data

volumes:
  dynamodb_data:
